# Docs: https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly

# Docs: https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - funlen
    - ginkgolinter
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/snyk/npmjs-deps-fetcher
  gofumpt:
    module-path: github.com/snyk/npmjs-deps-fetcher
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    confidence: 0
