version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

commands:
  setup_build_remote_docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

  build_image:
    steps:
      - run:
          name: Build Docker image
          command: make docker-build

jobs:
  test_and_build:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: /tmp/test-reports
      - setup_build_remote_docker
      - build_image

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-app-sec
          trusted-branch: main
      - test_and_build